In [1]:
#source: https://www.tensorflow.org/tutorials/quickstart/beginner

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2022-09-28 11:10:02.074337: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-28 11:10:02.237075: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-09-28 11:10:02.792482: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/cshetty2/anaconda3/envs/tf_v2/lib/
2022-09-28 11:10:02.792566: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libn

TensorFlow version: 2.10.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(1280, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(5120, activation='relu'),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2022-09-28 11:10:05.669594: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-28 11:10:07.440343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6646 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2080, pci bus id: 0000:19:00.0, compute capability: 7.5
2022-09-28 11:10:07.441091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 6646 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 2080, pci bus id: 0000:1a:00.0, compute capability: 7.5
2022-09-28 11:10:07.441735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/t

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.00036247,  0.00341535,  0.00240648,  0.00086086,  0.00275272,
         0.00814319,  0.00016253, -0.00078512, -0.00335089, -0.00165615]],
      dtype=float32)

In [5]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [6]:
loss_fn(y_train[:1], predictions).numpy()

2.2956052

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=1, batch_size=64)

938/938 [==============================] - 40s 43ms/step - loss: 1.6069 - accuracy: 0.3735


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 2s - loss: 1.1891 - accuracy: 0.5198 - 2s/epoch - 6ms/step


[1.1890606880187988, 0.5198000073432922]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.5986719e-06, 4.8292699e-01, 3.4075134e-04, 3.3214630e-05,
        1.2282315e-03, 4.8822176e-06, 1.2694366e-05, 5.0691396e-01,
        2.4783984e-03, 6.0582780e-03],
       [1.1151332e-01, 4.6296188e-04, 3.3098781e-01, 7.5569548e-02,
        5.3723110e-04, 2.3654296e-01, 2.3414542e-01, 1.7299158e-04,
        9.7960429e-03, 2.7165725e-04],
       [6.1666160e-06, 4.0059313e-01, 5.2561180e-04, 1.4479710e-04,
        7.8916885e-03, 2.6838414e-05, 2.1388922e-05, 5.6028646e-01,
        3.6064631e-03, 2.6897466e-02],
       [9.1352493e-01, 7.8915706e-20, 5.1006483e-04, 2.5635353e-11,
        3.8165387e-19, 3.7201033e-07, 8.5964635e-02, 1.6281823e-20,
        5.0452498e-17, 1.6079722e-22],
       [2.7384542e-05, 2.1820891e-01, 1.0272339e-03, 1.6948123e-03,
        1.2970850e-01, 4.8910984e-04, 5.3887972e-05, 4.1910204e-01,
        6.9346456e-03, 2.2275348e-01]], dtype=float32)>